

public_gsheets_url_DS1 = "https://docs.google.com/spreadsheets/d/15Czk7k6Ndy8KGOfF_5sAPq2J89yIHntiF3ydt2Pc6vU/edit#gid=0"
public_gsheets_url_DS2 = "https://docs.google.com/spreadsheets/d/1x2EFrGVv-VrQiC5sV1OMUV6C7dCDZP5RwBopMvwzRW8/edit#gid=0"
